# Generated by Django 5.1.2 on 2024-11-12 11:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('animals & pets', 'animals & pets'), ('anime', 'anime'), ('art & design', 'art & design'), ('auto & technique', 'auto & technique'), ('blogging', 'blogging'), ('cartoons', 'cartoons'), ('celebrity', 'celebrity'), ('dance', 'dance'), ('fashion & beauty', 'fashion & beauty'), ('food & kitchen', 'food & kitchen'), ('gaming', 'gaming'), ('live pictures', 'live pictures'), ('mashup', 'mashup'), ('memes', 'memes'), ('movies & TV', 'movies & TV'), ('music', 'music'), ('nature & travel', 'nature & travel'), ('science & technology', 'science & technology'), ('sports', 'sports'), ('stand-up & Jokes', 'stand-up & Jokes')], max_length=229)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('resized_photo', models.ImageField(blank=True, null=True, upload_to='resized_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('animals & pets', 'animals & pets'), ('anime', 'anime'), ('art & design', 'art & design'), ('auto & technique', 'auto & technique'), ('blogging', 'blogging'), ('cartoons', 'cartoons'), ('celebrity', 'celebrity'), ('dance', 'dance'), ('fashion & beauty', 'fashion & beauty'), ('food & kitchen', 'food & kitchen'), ('gaming', 'gaming'), ('live pictures', 'live pictures'), ('mashup', 'mashup'), ('memes', 'memes'), ('movies & TV', 'movies & TV'), ('music', 'music'), ('nature & travel', 'nature & travel'), ('science & technology', 'science & technology'), ('sports', 'sports'), ('stand-up & Jokes', 'stand-up & Jokes')], max_length=229)),
                ('video', models.FileField(max_length=255, upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
