# Generated by Django 5.1.2 on 2024-11-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_stream', '0002_photo_likes_video_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='resized_photo',
        ),
    ]
