# Generated by Django 5.1.2 on 2024-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_stream', '0006_alter_photo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
