# Generated by Django 5.1.2 on 2025-01-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_stream', '0007_alter_photo_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='code/media/photos/'),
        ),
    ]
