# Generated by Django 5.1.2 on 2024-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsphoto',
            name='text',
            field=models.TextField(default=1, max_length=2000, verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentsvideo',
            name='text',
            field=models.TextField(default='default text', max_length=2000, verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
