# Generated by Django 5.1.2 on 2024-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likesphoto',
            unique_together=set(),
        ),
    ]
