# Generated by Django 5.1.2 on 2024-11-19 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0003_likesphoto_username'),
        ('media_stream', '0005_alter_photo_likes_alter_video_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesphoto',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='likesphoto',
            unique_together={('user', 'photo')},
        ),
    ]
