# Generated by Django 5.1.2 on 2024-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='WY6=HfwS"{', max_length=150, unique=True),
        ),
    ]
