# Generated by Django 5.1.2 on 2024-11-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0004_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='VnucW!nFTE', max_length=150, unique=True),
        ),
    ]
