# Generated by Django 5.1.2 on 2024-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0006_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='T_<J"kFxM0', max_length=150, unique=True),
        ),
    ]
