# Generated by Django 5.1.2 on 2024-12-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0127_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='-[]-iu1U@p', max_length=150, unique=True),
        ),
    ]
