# Generated by Django 5.1.2 on 2025-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0157_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='}>yxHkk<h\\', max_length=150, unique=True),
        ),
    ]
