# Generated by Django 5.1.2 on 2025-01-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0188_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='p1+usU|K%m', max_length=150, unique=True),
        ),
    ]
