# Generated by Django 5.1.2 on 2025-01-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0190_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='TF4=bSr/@%', max_length=150, unique=True),
        ),
    ]
