# Generated by Django 5.1.2 on 2025-01-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0216_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='3L1}]4{bNK', max_length=150, unique=True),
        ),
    ]
