# Generated by Django 5.1.2 on 2025-01-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization_token', '0219_alter_authorizationuserontoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationuserontoken',
            name='username',
            field=models.CharField(blank=True, default='=L\\Hak%bR<', max_length=150, unique=True),
        ),
    ]
