# Generated by Django 5.1.2 on 2024-11-16 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comments', '0002_commentsphoto_text_commentsvideo_text'),
        ('media_stream', '0003_remove_photo_resized_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsOnPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Прочитано?')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Comments.commentsphoto', verbose_name='Комментарий')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_notifications', to='media_stream.photo', verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление для фото',
                'verbose_name_plural': 'Уведомления для фото',
            },
        ),
    ]
